[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "nodejs-18_x", "postgresql"]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "npm install",
    "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "./start.sh"

[variables]
PYTHON_VERSION = "3.11.0"
NODE_VERSION = "18.17.0"