providers = ["nodejs", "python"]

[variables]
NODE_ENV = "production"
NEXT_TELEMETRY_DISABLED = "1"
PORT = "3000"
AGENT_API_PORT = "8080"
DEPLOYMENT_ENV = "railway"

[phases.build]
cmds = [
    "npm ci --production=false",
    "npm run build",
    "pip install --no-cache-dir -r requirements.txt"
]

[phases.start]
cmd = "./start-agent-ui.sh"